table 'Employees Separations Tracker'
	lineageTag: c94a3ec7-b263-40f9-8c64-7edfc7c0db5b

	measure 'Total Exits' = (COUNTROWS('Employees Separations Tracker'))
		formatString: 0
		lineageTag: 5e038f72-141a-4537-8136-d37c083fcdda

	measure 'Exits (Current Year by Last Day)' =
			
			COALESCE(
			    CALCULATE(
			        COUNTROWS('Employees Separations Tracker'),
			        'Dim_Date'[Year] = YEAR(TODAY())
			    ),
			    0
			)
		formatString: 0
		lineageTag: 8f605714-c400-4f47-9eb7-63919158a4ca

	measure 'Exits (CY by Last Day)' = ```
			
			COALESCE(
			    CALCULATE(
			        COUNTROWS('Employees Separations Tracker'),
			        'Dim_Date'[Year] = YEAR(TODAY())
			    ),
			    0
			)
			
			```
		formatString: 0
		lineageTag: 3288ea08-6a30-446b-8418-e2579e303f04

	measure 'Total Exits LY' = CALCULATE([Total Exits], SAMEPERIODLASTYEAR('Dim_Date'[Date]))
		formatString: 0
		lineageTag: e49159aa-558c-472b-99a1-5f8e20ae1762

	measure 'Exits YoY' = DIVIDE([Total Exits] - [Total Exits LY], [Total Exits LY])
		lineageTag: a41a9a83-6f9c-4c8c-b3b6-55b09b22d3a0

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column RowNumber
		dataType: string
		lineageTag: bf80b169-5d2a-43df-8934-b52933f52bdb
		summarizeBy: none
		sourceColumn: RowNumber

		annotation SummarizationSetBy = Automatic

	column 'Email Status'
		dataType: string
		lineageTag: f82cde55-472d-49f3-a609-d62f0cb6f610
		summarizeBy: none
		sourceColumn: Email Status

		annotation SummarizationSetBy = Automatic

	column 'Employee First Name'
		dataType: string
		lineageTag: d6928645-0cae-4faf-a716-175ee32bca9e
		summarizeBy: none
		sourceColumn: Employee First Name

		annotation SummarizationSetBy = Automatic

	column 'Employee Last Name'
		dataType: string
		lineageTag: 0935b83b-3d06-4762-9e5b-b065e15f1947
		summarizeBy: none
		sourceColumn: Employee Last Name

		annotation SummarizationSetBy = Automatic

	column 'Staff Email'
		dataType: string
		lineageTag: 1f77b8b8-9571-4f2f-90b7-1e5d7b2aeafa
		summarizeBy: none
		sourceColumn: Staff Email

		annotation SummarizationSetBy = Automatic

	column 'Position ID'
		dataType: string
		lineageTag: bcc30d53-7e0a-4a46-9347-d2419497d34e
		summarizeBy: none
		sourceColumn: Position ID

		annotation SummarizationSetBy = Automatic

	column 'Reason for Exit'
		dataType: string
		lineageTag: 7bcd52e3-9796-4b2b-8cac-aa04ae29bec6
		summarizeBy: none
		sourceColumn: Reason for Exit

		annotation SummarizationSetBy = Automatic

	column 'Last Day Date'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 9c850059-65e5-4ebd-9d6c-a260e65f80ab
		summarizeBy: none
		sourceColumn: Last Day Date

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Separation ID'
		dataType: string
		lineageTag: 03078d57-cf62-4bef-a103-a7bead143339
		summarizeBy: none
		sourceColumn: Separation ID

		annotation SummarizationSetBy = Automatic

	column 'Employee ID'
		dataType: string
		lineageTag: ad126b83-4f4f-47bd-b5e6-325b51270117
		summarizeBy: none
		sourceColumn: Employee ID

		annotation SummarizationSetBy = Automatic

	column 'Date Form Submitted'
		dataType: string
		lineageTag: 5d2d9d4a-6340-45fd-881c-2b34d567c024
		summarizeBy: none
		sourceColumn: Date Form Submitted

		annotation SummarizationSetBy = Automatic

	column 'Separated Pay Period'
		dataType: string
		lineageTag: 94aae620-f99f-4b59-90a2-52483941a88f
		summarizeBy: none
		sourceColumn: Separated Pay Period

		annotation SummarizationSetBy = Automatic

	column 'Separated Payroll Starting Date'
		dataType: string
		lineageTag: 6ba47006-935d-47b7-a1d3-290b58eaa464
		summarizeBy: none
		sourceColumn: Separated Payroll Starting Date

		annotation SummarizationSetBy = Automatic

	column 'Separated Payroll Ending Date'
		dataType: string
		lineageTag: 8528fa74-f1d0-4378-842b-b4d74de479e4
		summarizeBy: none
		sourceColumn: Separated Payroll Ending Date

		annotation SummarizationSetBy = Automatic

	column 'Separated Final Pay Date'
		dataType: string
		lineageTag: ec5ea6f5-6a8d-4947-bfe4-c35bf9e66d51
		summarizeBy: none
		sourceColumn: Separated Final Pay Date

		annotation SummarizationSetBy = Automatic

	column 'Insurance Last Date'
		dataType: string
		lineageTag: f9fbfb73-3735-4232-abf1-ecab57335db5
		summarizeBy: none
		sourceColumn: Insurance Last Date

		annotation SummarizationSetBy = Automatic

	column 'Job Class Level'
		dataType: string
		lineageTag: 9ecd1af7-a56d-48cb-bdf1-79b4ee0bca27
		summarizeBy: none
		sourceColumn: Job Class Level

		annotation SummarizationSetBy = Automatic

	column FullName
		dataType: string
		lineageTag: e423aadc-05a8-421b-b027-0cdc7b8c0d35
		summarizeBy: none
		sourceColumn: FullName

		annotation SummarizationSetBy = Automatic

	column 'Job Class'
		dataType: string
		lineageTag: 07f6eff0-57ae-483a-ab29-c94bcde8b753
		summarizeBy: none
		sourceColumn: Job Class

		annotation SummarizationSetBy = Automatic

	column 'Date Stayed' =
			
			DATEDIFF(
			    RELATED('Employees Tracker'[Start Date]),
			    'Employees Separations Tracker'[Last Day Date],
			    YEAR
			)
		formatString: 0
		lineageTag: 00fa8cd4-81d0-4eb4-a2f8-3b800dacb4b1
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	partition 'Employees Separations Tracker' = m
		mode: import
		source =
				let
				    Source = SmartsheetGlobal.Contents("US", []),
				    #"1134964738680708" = Source{[Key="1134964738680708"]}[Data],
				    #"6934380720482180" = #"1134964738680708"{[Key="6934380720482180"]}[Data],
				    #"6507921459335044" = #"6934380720482180"{[Key="6507921459335044"]}[Data],
				    #"Added Custom" = Table.AddColumn(#"6507921459335044", "FullName", each [Employee First Name] & " " & [Employee Last Name]),
				    #"Reordered Columns" = Table.ReorderColumns(#"Added Custom",{"RowNumber", "Date Form Submitted", "Separation ID", "Email Status", "Employee ID", "Employee First Name", "Employee Last Name", "FullName", "Staff Email", "Position ID", "Job Class Level", "Reason for Exit", "Last Day Date", "Separated Pay Period", "Separated Payroll Starting Date", "Separated Payroll Ending Date", "Separated Final Pay Date", "Insurance Last Date"})
				in
				    #"Reordered Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

