table 'Vacancies and Recruitments'
	lineageTag: 7e4b17bf-0644-4747-af01-a42da704aa05

	column RowNumber
		dataType: string
		lineageTag: dbae8d20-841c-48a0-9508-af6266fcd255
		summarizeBy: none
		sourceColumn: RowNumber

		annotation SummarizationSetBy = Automatic

	column 'Row Created Timestamp'
		dataType: string
		lineageTag: 8f03413a-48fd-4580-b24e-82ecad398e98
		summarizeBy: none
		sourceColumn: Row Created Timestamp

		annotation SummarizationSetBy = Automatic

	column 'Vacancy ID'
		dataType: string
		lineageTag: 5140ca7b-4cda-4859-9974-14bff39fbe67
		summarizeBy: none
		sourceColumn: Vacancy ID

		annotation SummarizationSetBy = Automatic

	column Dept
		dataType: string
		lineageTag: 5bfa72b9-00f0-4bb7-a22d-5f96083cca29
		summarizeBy: none
		sourceColumn: Dept

		annotation SummarizationSetBy = Automatic

	column PosID
		dataType: string
		lineageTag: c3b80629-a98b-46c2-b3e3-df7d92018b7e
		summarizeBy: none
		sourceColumn: PosID

		annotation SummarizationSetBy = Automatic

	column JobClassTitle
		dataType: string
		lineageTag: 2d9b5616-9a3c-4de6-a79d-e3487e74e28c
		summarizeBy: none
		sourceColumn: JobClassTitle

		annotation SummarizationSetBy = Automatic

	column Status
		dataType: string
		lineageTag: f319380c-cde6-433b-b4db-f0f6e19576a1
		summarizeBy: none
		sourceColumn: Status

		annotation SummarizationSetBy = Automatic

	column Label
		dataType: string
		lineageTag: 1afee4ec-f34a-46a7-9a58-48e28c78d5ad
		summarizeBy: none
		sourceColumn: Label

		annotation SummarizationSetBy = Automatic

	column 'Vacancy Start Date'
		dataType: dateTime
		formatString: mm/dd/yyyy
		lineageTag: 1a9b5024-c5c3-42dc-855e-f5bc882bc3ca
		summarizeBy: none
		sourceColumn: Vacancy Start Date

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column 'Date Filled'
		dataType: dateTime
		formatString: mm/dd/yyyy
		lineageTag: 5e4990fa-d965-45d8-9129-c4d4ca63fb3e
		summarizeBy: none
		sourceColumn: Date Filled

		variation Variation
			isDefault
			relationship: cb23ea84-53e1-4ff5-94d1-23ca0ee12b28
			defaultHierarchy: LocalDateTable_31afe02b-a694-40ef-b4d1-6942f8aa4f21.'Date Hierarchy'

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column 'Vacancy Days Open'
		dataType: int64
		formatString: 0
		lineageTag: c32ccaeb-bf15-4551-b3b9-bf3b9ce724af
		summarizeBy: none
		sourceColumn: Vacancy Days Open

		changedProperty = DataType

		annotation SummarizationSetBy = User

	column 'Recruitment Type'
		dataType: string
		lineageTag: 250e69d6-4e44-467c-a74b-8d1d22192b04
		summarizeBy: none
		sourceColumn: Recruitment Type

		annotation SummarizationSetBy = Automatic

	column 'Interviews Conducted'
		dataType: int64
		formatString: 0
		lineageTag: 4f232297-990e-4830-acf2-d3dc3de6aad6
		summarizeBy: sum
		sourceColumn: Interviews Conducted

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

	column 'Is Active'
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: e798daf0-ca32-4606-97ee-0c0caf30b840
		summarizeBy: none
		sourceColumn: Is Active

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

	partition 'Vacancies and Recruitments' = m
		mode: import
		source =
				let
				    Source = SmartsheetGlobal.Contents("US", null),
				    #"1134964738680708" = Source{[Key="1134964738680708"]}[Data],
				    #"38243791071108" = #"1134964738680708"{[Key="38243791071108"]}[Data],
				    #"4963448636002180" = #"38243791071108"{[Key="4963448636002180"]}[Data],
				    #"Added Custom" = Table.AddColumn(#"4963448636002180", "Is Active", each Text.Upper(Text.Trim([Status])) <> "FILLED"),
				    #"Replaced Value" = Table.ReplaceValue(#"Added Custom",null,"TBA",Replacer.ReplaceValue,{"Recruitment Type"}),
				    #"Replaced Value1" = Table.ReplaceValue(#"Replaced Value",null,0,Replacer.ReplaceValue,{"Interviews Conducted"}),
				    #"Replaced Value2" = Table.ReplaceValue(#"Replaced Value1",null,"TBD",Replacer.ReplaceValue,{"Label"})
				in
				    #"Replaced Value2"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

